# Generated by Django 5.2.4 on 2025-08-04 14:47

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100, unique=True, verbose_name='Nome da Loja')),
                ('cnpj', models.CharField(max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('layout', models.CharField(default='standard', max_length=50, verbose_name='Layout')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
                ('page', models.ImageField(blank=True, null=True, upload_to='page/', verbose_name='Imagem da Principal')),
                ('main', models.TextField(blank=True, verbose_name='Texto Principal')),
                ('draft', models.ImageField(blank=True, null=True, upload_to='draft/', verbose_name='Imagem de Destaque')),
                ('text', models.TextField(blank=True, verbose_name='Descrição Adicional')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('primary_color', colorfield.fields.ColorField(choices=[('#0b2545', 'Azul Profundo'), ('#e91e63', 'Rosa Claro'), ('#3f51b5', 'Azul Médio'), ('#fdd835', 'Amarelo Claro'), ('#ffb74d', 'Laranja Suave'), ('#ef5350', 'Vermelho Suave'), ('#ba68c8', 'Roxo Claro'), ('#4db6ac', 'Verde Água'), ('#c62828', 'Vermelho Pizzaria'), ('#2e4d38', 'Verde Musgo Escuro'), ('#3a0b52', 'Roxo Beringela'), ('#2e2e2e', 'Grafite Escuro'), ('#7b1e1e', 'Vermelho Vinho'), ('#8b4513', 'Marrom Queimado'), ('#665c1e', 'Mostarda Escura')], default='#0b2545', image_field=None, max_length=7, samples=None, verbose_name='Cor Primária')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Loja',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Loja')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
