# Generated by Django 5.2.4 on 2025-07-25 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('layout', models.CharField(default='standard', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('page', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('main', models.TextField(blank=True)),
                ('draft', models.ImageField(blank=True, null=True, upload_to='draft/')),
                ('text', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
