# Generated by Django 5.2.4 on 2025-08-05 13:04

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='draft',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.user_directory_path, verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.user_directory_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='store',
            name='page',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.user_directory_path, verbose_name='Imagem da Principal'),
        ),
    ]
