# Generated by Django 5.2.4 on 2025-07-25 18:20

import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='draft',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.PathRename('img/store/draft/')),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.PathRename('img/store/logo/')),
        ),
        migrations.AlterField(
            model_name='store',
            name='page',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.PathRename('img/store/page/')),
        ),
        migrations.AlterField(
            model_name='store',
            name='store',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
