# Generated by Django 5.2.4 on 2025-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_cnpj_alter_store_draft_alter_store_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
    ]
