# Generated by Django 5.2.4 on 2025-08-01 12:24

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_store_draft_alter_store_logo_alter_store_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=colorfield.fields.ColorField(choices=[('#0b2545', 'Azul Profundo'), ('#e91e63', 'Rosa Claro'), ('#3f51b5', 'Azul Médio')], default='#0B2545', image_field=None, max_length=7, samples=None),
        ),
    ]
