# Generated by Django 5.2.4 on 2025-08-01 12:46

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_primary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='primary_color',
            field=colorfield.fields.ColorField(choices=[('#0b2545', 'Azul Profundo'), ('#e91e63', 'Rosa Claro'), ('#3f51b5', 'Azul Médio'), ('#fdd835', 'Amarelo Claro'), ('#ffb74d', 'Laranja Suave'), ('#ef5350', 'Vermelho Suave'), ('#ba68c8', 'Roxo Claro'), ('#4db6ac', 'Verde Água'), ('#c62828', 'Vermelho Pizzaria'), ('#2e4d38', 'Verde Musgo Escuro'), ('#3a0b52', 'Roxo Beringela'), ('#2e2e2e', 'Grafite Escuro'), ('#7b1e1e', 'Vermelho Vinho'), ('#8b4513', 'Marrom Queimado'), ('#665c1e', 'Mostarda Escura')], default='#0B2545', image_field=None, max_length=7, samples=None),
        ),
    ]
