# Generated by Django 5.2.4 on 2025-08-01 15:13

import colorfield.fields
import django.db.models.deletion
import store.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_store_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Loja'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='store',
            name='cnpj',
            field=models.CharField(max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='store',
            name='draft',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.PathRename('draft/'), verbose_name='Imagem de Destaque'),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='layout',
            field=models.CharField(default='standard', max_length=50, verbose_name='Layout'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.PathRename('logo/'), verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='store',
            name='main',
            field=models.TextField(blank=True, verbose_name='Texto Principal'),
        ),
        migrations.AlterField(
            model_name='store',
            name='page',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.PathRename('page/'), verbose_name='Imagem da Principal'),
        ),
        migrations.AlterField(
            model_name='store',
            name='primary_color',
            field=colorfield.fields.ColorField(choices=[('#0b2545', 'Azul Profundo'), ('#e91e63', 'Rosa Claro'), ('#3f51b5', 'Azul Médio'), ('#fdd835', 'Amarelo Claro'), ('#ffb74d', 'Laranja Suave'), ('#ef5350', 'Vermelho Suave'), ('#ba68c8', 'Roxo Claro'), ('#4db6ac', 'Verde Água'), ('#c62828', 'Vermelho Pizzaria'), ('#2e4d38', 'Verde Musgo Escuro'), ('#3a0b52', 'Roxo Beringela'), ('#2e2e2e', 'Grafite Escuro'), ('#7b1e1e', 'Vermelho Vinho'), ('#8b4513', 'Marrom Queimado'), ('#665c1e', 'Mostarda Escura')], default='#0B2545', image_field=None, max_length=7, samples=None, verbose_name='Cor Primária'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da Loja'),
        ),
        migrations.AlterField(
            model_name='store',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='store',
            name='text',
            field=models.TextField(blank=True, verbose_name='Descrição Adicional'),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='store',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
