# Generated by Django 5.2.4 on 2025-08-04 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('photo', models.ImageField(upload_to='product/', verbose_name='Foto')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('stock', models.PositiveIntegerField(verbose_name='Quantidade no Estoque')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store', verbose_name='Nome da Loja')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store', verbose_name='Nome da Loja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinho',
            },
        ),
    ]
