# Generated by Django 5.2.4 on 2025-08-05 13:04

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to=product.models.user_directory_path, verbose_name='Foto'),
        ),
    ]
